# Generated by Django 4.2.1 on 2023-08-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('img', models.ImageField(upload_to='background/')),
            ],
        ),
        migrations.CreateModel(
            name='my_User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=400, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('img', models.ImageField(default='/user_icon/merkimer.jpg', upload_to='user_icon/')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=100, null=True)),
                ('description', models.CharField(max_length=400)),
                ('choice_option_name', models.CharField(default='no_choice', max_length=70)),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='editor.location')),
                ('previous', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='editor.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('R', 'Replic'), ('A', 'Arrival/Leave'), ('T', 'Show Title')], default='R', max_length=1)),
                ('next', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_event', to='editor.sceneevent')),
                ('previous', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_event', to='editor.sceneevent')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='editor.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Your title', max_length=100)),
                ('description', models.CharField(default='Here you can add description', max_length=600)),
                ('img', models.ImageField(upload_to='posters/')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('start', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_to_begin', to='editor.scene')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='states/')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='editor.hero')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('img', models.ImageField(upload_to='title_background/')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='editor.sceneevent')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='editor.story'),
        ),
        migrations.CreateModel(
            name='Replic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=400)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replic', to='editor.sceneevent')),
                ('hero_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replics', to='editor.state')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='story',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='editor.story'),
        ),
        migrations.AddField(
            model_name='hero',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='editor.story'),
        ),
        migrations.CreateModel(
            name='ArrivalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Arrival'), ('L', 'Leave')], default='A', max_length=1)),
                ('img', models.ImageField(upload_to='arrival_leave_imgs/')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arraival', to='editor.sceneevent')),
                ('hero_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='editor.state')),
            ],
        ),
    ]
