# Generated by Django 4.2.1 on 2023-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='img',
            field=models.ImageField(default='states/default.jpg', upload_to='states/'),
        ),
    ]
